### ISSUE TITLE
Navbar responsive issue

### ISSUE THREAD

**Issue by shubhamjain-24** [shubhamjain-24/fliqaIndia#1]

**Comment by michagodfrey** [comment]
Hi shubhamjain, I forked the project and can see the navbar responsive issue. Can I try to fix it?

**Comment by shubhamjain-24** [comment]
> Hi shubhamjain, I forked the project and can see the navbar responsive issue. Can I try to fix it

Hello for sure it will be really helpfull

**Comment by michagodfrey** [comment]
Great, thanks. I'll make a start today.

**Comment by DHRUVKHANDELWAL00** [comment]
hey @shubhamjain-24 ,can i also try it out?

**Comment by shubhamjain-24** [comment]
> Great, thanks. I'll make a start today.

It will be great if you could do that before 5PM IST

**Comment by shubhamjain-24** [comment]
> hey @shubhamjain-24 ,can i also try it out?

Hello @DHRUVKHANDELWAL00   sure you can try it, and it will be great if you can do that before 5PM IST

**Comment by michagodfrey** [comment]
Hi @shubhamjain-24 @DHRUVKHANDELWAL00 

Just made a pull request, hope you like it. And thanks for letting me have a go, from looking at your code I see we have very different approaches, and that's what makes this so good for learning.

**Comment by shubhamjain-24** [comment]
> Hi @shubhamjain-24 @DHRUVKHANDELWAL00
> 
> Just made a pull request, hope you like it. And thanks for letting me have a go, from looking at your code I see we have very different approaches, and that's what makes this so good for learning.

Thank you for your support can you please share images of the design in phone view as well as in desktop view it will be really helpful for me to understand things 😊😊

**Comment by michagodfrey** [comment]
Here you are. I kept your code in tact where I could. So you still have the same cool animation for the bars. I wasn't sure about the layout you envisioned, so this is what I came up with.  

Desktop:
![desktop](https://user-images.githubusercontent.com/40159415/201576930-3590413d-2850-4fbc-b6d2-d54fac7b69cd.png)

Tablet (with side menu active):
![tablet](https://user-images.githubusercontent.com/40159415/201577248-8951c15d-75db-4acc-b93b-9def2f7aabf6.png)

Mobile:
![mobile](https://user-images.githubusercontent.com/40159415/201577289-10553a66-5b08-48a3-a0aa-fa8b7b2fd9c9.png)

**Comment by michagodfrey** [comment]
I'll just add two points:

- The tablet view looks a bit cut off on the right, that's the image, not the app. Sorry about that. Also, that side menu has a nice slide animation from the right. 
- It is spelt 'Community' I saw you spelt it 'comunnity' then I changed it to 'comunity' trying to fix it. Anyway, easy to solve if you merge this change.

**Comment by shubhamjain-24** [comment]
> Here you are. I kept your code in tact where I could. So you still have the same cool animation for the bars. I wasn't sure about the layout you envisioned, so this is what I came up with.
> 
> Desktop: ![desktop](https://user-images.githubusercontent.com/40159415/201576930-3590413d-2850-4fbc-b6d2-d54fac7b69cd.png)
> 
> Tablet (with side menu active): ![tablet](https://user-images.githubusercontent.com/40159415/201577248-8951c15d-75db-4acc-b93b-9def2f7aabf6.png)
> 
> Mobile: ![mobile](https://user-images.githubusercontent.com/40159415/201577289-10553a66-5b08-48a3-a0aa-fa8b7b2fd9c9.png)

I liked it very much thank you for your support i just want one thing it will be great if you will do it can you please shift the nav items to right about 100px basically i don't want in middle its should be bit left from the middle it will be really grateful if you will do it

**Comment by michagodfrey** [comment]
Ok, quick fix, I made another pull request and attached an image. I think that's what you mean. If the nav items are not exactly where you want, it will be easy to adjust after a merge. Just edit the position of 
`
@media (min-width: 1200px) {
  .Navbar>.logo-optionWrapper>.nav-items {
    position: absolute;
    left: 20%;
  }
}
`
in navbar.css to where you want. 

![desktop-off-center-menu](https://user-images.githubusercontent.com/40159415/201611796-99121477-d3fe-4730-8dc9-a67abab7586b.png)

Also, there are some responsive issues with some of the other sections I think. But the navbar seems to be working well.

**Comment by shubhamjain-24** [comment]
> Ok, quick fix, I made another pull request and attached an image. I think that's what you mean. If the nav items are not exactly where you want, it will be easy to adjust after a merge. Just edit the position of `@media (min-width: 1200px) { .Navbar>.logo-optionWrapper>.nav-items { position: absolute; left: 20%; } }` in navbar.css to where you want.
> 
> ![desktop-off-center-menu](https://user-images.githubusercontent.com/40159415/201611796-99121477-d3fe-4730-8dc9-a67abab7586b.png)
> 
> Also, there are some responsive issues with some of the other sections I think. But the navbar seems to be working well.

Thanks a lot for you help 😊😊
